services:
  svelte-nginx:
    build:
      context: .
      dockerfile: Dockerfile.svelte-nginx
    container_name: svelte-nginx
    expose: # so caddy can reverse proxy to nginx
      - "80"

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: caddy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - GODADDY_EMAIL=${GODADDY_EMAIL}
      - GODADDY_TOKEN=${GODADDY_TOKEN}

volumes:
  caddy_data:
  caddy_config:
